mode1:
  pos: 1.0
  rot: 0.3

mode2:
  pos: 1.0
  rot: 0.0

mode3:
  pos: 0.0
  rot: 0.3

mode4:
  pos: 0.5
  rot: 0.2

mode5:
  pos: 0.5
  rot: 0.0

mode6:
  pos: 0.0
  rot: 0.2

mode7:
  pos: 2.0
  rot: 0.5

mode8:
  pos: 2.0
  rot: 0

mode9:
  pos: 0
  rot: 0.5