/**:
    ros__parameters:
        robot_description_kinematics:
            robot0_manipulator:
                kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
                kinematics_solver_search_resolution: 0.05
                kinematics_solver_timeout: 0.05
                kinematics_solver_attempts: 3
            robot1_manipulator:
                kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
                kinematics_solver_search_resolution: 0.05
                kinematics_solver_timeout: 0.05
                kinematics_solver_attempts: 3
            robot2_manipulator:
                kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
                kinematics_solver_search_resolution: 0.05
                kinematics_solver_timeout: 0.05
                kinematics_solver_attempts: 3
            robot3_manipulator:
                kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
                kinematics_solver_search_resolution: 0.05
                kinematics_solver_timeout: 0.05
                kinematics_solver_attempts: 3